version: "3"

services:

    emscripten-build:
        image: "trzeci/emscripten"
        volumes:
            - ".:/src"
        command: |
            /bin/bash -c "
                cd buildd/emscripten
                bash emscripten-build.sh
            "
